import org.gradle.api.file.DuplicatesStrategy
import org.gradle.api.tasks.Delete

plugins {
    java
    id("net.neoforged.moddev")
}

val modId = "clutchperms"
val commonProject = project(":common")
val minecraftVersion: String by project
val minecraftVersionRange: String by project
val neoForgeVersion: String by project
val neoForgeVersionRange: String by project
val hikariCpVersion: String by project
val sqliteJdbcVersion: String by project
val modVersion = project.version.toString()
val bundledLibraries by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

evaluationDependsOn(commonProject.path)

neoForge {
    version = neoForgeVersion

    runs {
        register("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }
    }

    mods {
        register(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

dependencies {
    implementation(commonProject)
    implementation("com.zaxxer:HikariCP:$hikariCpVersion")
    implementation("org.xerial:sqlite-jdbc:$sqliteJdbcVersion")
    bundledLibraries("com.zaxxer:HikariCP:$hikariCpVersion")
    bundledLibraries("org.xerial:sqlite-jdbc:$sqliteJdbcVersion")
    add("jarJar", commonProject)
}

sourceSets.test {
    compileClasspath += sourceSets.main.get().compileClasspath
    runtimeClasspath += sourceSets.main.get().runtimeClasspath
}

tasks.processResources {
    val replaceProperties =
        mapOf(
            "minecraftVersion" to minecraftVersion,
            "minecraftVersionRange" to minecraftVersionRange,
            "neoForgeVersion" to neoForgeVersion,
            "neoForgeVersionRange" to neoForgeVersionRange,
            "version" to modVersion,
        )

    inputs.properties(replaceProperties)

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(replaceProperties)
    }
}

val cleanGeneratedLogs by tasks.registering(Delete::class) {
    group = "verification"
    description = "Deletes NeoForge logs generated by local test and build tasks."
    delete(layout.projectDirectory.dir("logs"))
}

tasks.named("test") {
    finalizedBy(cleanGeneratedLogs)
}

tasks.named("check") {
    finalizedBy(cleanGeneratedLogs)
}

tasks.named("build") {
    finalizedBy(cleanGeneratedLogs)
}

tasks.jar {
    from({
        bundledLibraries.map { zipTree(it) }
    }) {
        exclude("fabric.mod.json", "plugin.yml", "META-INF/mods.toml", "META-INF/neoforge.mods.toml")
        exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
        exclude("module-info.class", "META-INF/versions/**/module-info.class")
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.test {
    dependsOn(tasks.jar)
    systemProperty("clutchperms.jar", tasks.jar.get().archiveFile.get().asFile.absolutePath)
}
