name: ClutchPerms
version: ${version}
main: me.clutchy.clutchperms.paper.ClutchPermsPaperPlugin
description: Shared permission scaffolding for Paper.
api-version: "26.1.2"
permissions:
  clutchperms.admin:
    description: Allows access to ClutchPerms commands.
    default: op
